In [48]:
import numpy as np

**Simple Numpy**


In [49]:
#numpy arrays                  1d
list1=[10,20,30,40,50]
array1=np.array(list1)
print(array1)
type(array1)     #to find type of array

[10 20 30 40 50]


numpy.ndarray

In [50]:
#agr list m sary int num hun sirf 1 b float ho to sari list ka output float mein aye ga
#as it is jb sary float hun to aik b int ho to output int mein ho gi
#isi trah agr aik b chracter ho to sb chracter value m convert ho jy gy it means output chr m a jy gi.
#lkn agr hm chahy k int data m koi float value ki wja sy data type chang na ho to hm 
# [np.array(list1) k sath dtype=int,float,chr likh dy gy.
#np.array(list1,dtype=U32) b likh skty hn.

array1=np.array(list1,dtype='U32')
array1


array(['10', '20', '30', '40', '50'], dtype='<U32')

In [51]:
array1=np.array(list1,dtype='float')            #1d
array1

array([10., 20., 30., 40., 50.])

In [52]:
list=[1.2,3.5,7.9,4.5]            #1d
arr=np.array(list)
arr

array([1.2, 3.5, 7.9, 4.5])

In [53]:
#chng data type            1d
arr=np.array(list,dtype='int')
arr

array([1, 3, 7, 4])

In [54]:
arr=np.array(list,dtype='U32')   #for char data type   1d
arr

array(['1.2', '3.5', '7.9', '4.5'], dtype='<U32')

In [55]:
#tow dimentional array     2d
#2 dimentional array m rows or columns hoty hn is ko bnany k liye hm neasted (list list k under list)
#  use krty hn. 3 rows or 3 columns k set ko hm 3x3 ka metrics b kehty hn.
list2=[[10,20,30],[40,45,50],[55,60,65]]
arr=np.array(list2)
arr

array([[10, 20, 30],
       [40, 45, 50],
       [55, 60, 65]])

In [56]:
#create array by using arange    1d
arr=np.arange(1,16)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [57]:
#2 dimentional array by using arange          2d
#reshape aik attribute hai jiska mtlb hai btana shape dena k kitni row or column hun.
#jitny elements hun gy us k according reshape krna.
arr=np.arange(1,16).reshape((3,5))
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [58]:
arr=np.arange(1,21).reshape((5,4))
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [59]:
#matrix od zeros create krny k liye.    1d
arr=np.zeros(4)
arr

array([0., 0., 0., 0.])

In [60]:
#1d k liye single brckt or 2d k liye double brckt use krty hn. 2d
arr=np.zeros((4,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [61]:
#same as one k liye b yehi code 1d k liye single brckt or 2d k liye double brckt use ho gi.
arr=np.ones(6)        #1d

arr1=np.ones((2,3))        #2d

arr,arr1

(array([1., 1., 1., 1., 1., 1.]),
 array([[1., 1., 1.],
        [1., 1., 1.]]))

****Attributes of Numpy Array****

In [ ]:
#some attributes of numpy array 
1#- ndim
#array ka dimention find krny k liye (ndim) it means k yeh array jo hmny create kiya hai 
#wo 1d hai 2d hai ya 3d hai.

2#- Shape
#shape find kry k liye let suppose k 2d hai to kitni rows hain or kitny columns hai according to elements.

3#- size
#size find krny k liye let suppose 3 rows hain 2 column hn to un m element kitny hungy (3x2=6)&
#(2x3=6) is trah size find krty hn.

4#- dtype
#data ki type find krny k liye ye attribute use ho ga k aik array m sary element int hain 
# float hain ya chr hn apni need k according data type b set kr skty hn.

5#- itemsize
#let suppose 1 array create kiya usky under sary int hain to wo 1 int kitny bite ka hai.
#kitny bite memory m space ly rha h. int k size 4bit , float ka 8bit.
#  

Create Arrays use Attributes

In [ ]:
import numpy as np
list=[10,15,20,25,30]
arr=np.array(list)
arr


array([10, 15, 20, 25, 30])

In [73]:
ar=np.ndim(list)
print(ar)
arr

1


1

In [70]:
a=np.array([[1,2,3,4],[5,6,7,8]])
arr=np.ndim(a)
print(a)
arr

[[1 2 3 4]
 [5 6 7 8]]


2

In [71]:
b=np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
arr=np.ndim(b)
print(b)
arr

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


3

In [ ]:
arr=np.shape(a)              #2d
print(a)
arr

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

In [ ]:
arr=np.shape(b)                   #3d
print(b)
arr

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


(1, 3, 4)

In [80]:
arr=np.size(a)              #2d
print(a)
arr

[[1 2 3 4]
 [5 6 7 8]]


8

In [81]:
arr=np.size(b)                   #3d
print(b)
arr

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


12

In [85]:
import numpy as np
list=[10,15,20,25,30]
arr=np.array(list)
arr.dtype


dtype('int64')

In [90]:
import numpy as np
list=[1.2,1.5,2.2,2.5,3.3]
arr=np.array(list)
arr.dtype


dtype('float64')

In [86]:
import numpy as np
list=[10,15,20,25,30]
arr=np.array(list)
arr.itemsize


8

In [87]:
import numpy as np
list=[1.2,1.5,2.0,2.5,3.0]
arr=np.array(list)
arr.itemsize


8